### ISSUE TITLE
节点点击的时候气泡弹窗不显示

### ISSUE THREAD

**Issue by UCSBGauchos** [murongqimiao/DAG-diagram#16]
你好，我们在使用这个组件的时候，点击节点的时候气泡弹窗不显示，想问一下是什么原因，谢谢

**Comment by UCSBGauchos** [comment]
![pop](https://user-images.githubusercontent.com/5027742/72417199-543a4500-37b3-11ea-8295-fa9d4454d246.png)
node-pop是已经存在的

**Comment by murongqimiao** [comment]
感谢使用, 马上处理, 如果有类似问题的朋友可以入q群沟通 

if u have the same question plz join the Q group 793841737,  i will do my best , bro~

**Comment by murongqimiao** [comment]
this issue has resolved in version 0.1.22, plz install the latest version to avoid.

the reason is that   DOM element [foreignObject] has default attr [ overflow: hidden ] in some Chrome version. i had append the css attribute overflow: visible in  `main-body.js`

**Comment by UCSBGauchos** [comment]
> this issue has resolved in version 0.1.22, plz install the latest version to avoid.
> 
> the reason is that DOM element [foreignObject] has default attr [ overflow: hidden ] in some Chrome version. i had append the css attribute overflow: visible in `main-body.js`

Thank you so much. It works~
