### ISSUE TITLE
how to use this in vue3

### ISSUE THREAD

**Issue by jackli0909** [murongqimiao/DAG-diagram#24]
how to use this in vue3?
do you have plan to dev a vue3 version?

**Comment by murongqimiao** [comment]
got it , refactor it in vue3, will be done before 2023

**Comment by murongqimiao** [comment]
I have refector a new version of vue3.
use vite , vue3, sass, and elementUI
step to run example:
1. npm install -g joao-cli
2. joao init
3. cd new project  npm install && npm run dev
4. open loaclhost:5173
